### ISSUE TITLE
项目还在进展吗？

### ISSUE THREAD

**Issue by FelixSeptem** [developer-learning/paper-reading#8]
想问下项目的进展情况，以及论文的选题方向

**Comment by yangwenmai** [comment]
项目停滞了，因为人很少，你愿意参加？

我现在只是偶尔看看。

**Comment by FelixSeptem** [comment]
> 项目停滞了，因为人很少，你愿意参加？

有兴趣参加，想一起讨论distributed system相关的论文，不知道会不会有人感兴趣

**Comment by yangwenmai** [comment]
可以啊，先罗列一下哪些论文？然后做一个计划，咱们就可以开始。

**Comment by yangwenmai** [comment]
项目重启，不过形式还没有确定
